name: Docker Image CI
run-name: drive-gooder deploy ${{ github.actor }}

on:
  push:
    branches: ["prod"]
  pull_request:
    branches: ["prod"]
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  build-frontend:
    name: Build Frontend
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - name: Checkout branch
        uses: actions/checkout@v4

      - name: Build FE
        run: |
          cd web
          npm install

      - name: Build FE
        run: |
          cd web
          npm run build
          # FE build will be in build

      - uses: actions/upload-artifact@v4
        with:
          name: frontend-${{ github.sha }}
          path: web/build

  build-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    environment: prod
    needs: [build-frontend]
    steps:
      - name: Checkout branch
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ vars.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Login to AWS ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Download Frontend Build
        uses: actions/download-artifact@v4
        with:
          name: frontend-${{ github.sha }}
          path: api/build

      - name: Build, tag, and push image to Amazon ECR
        id: build-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ${{ vars.ECR_REPOSITORY }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          cd api && docker build . -f cloud/Dockerfile -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          docker tag $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG $ECR_REGISTRY/$ECR_REPOSITORY:latest 
          docker push $ECR_REGISTRY/$ECR_REPOSITORY --all-tags
          echo "image=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG" >> $GITHUB_OUTPUT
